apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  APP_ENV: local
  APP_DEBUG: "true"
  SESSION_DRIVER: file
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: mydb

