apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: todo
type: Opaque
data:
  mysql-user: dXNlcg==  # user (base64 encoded)
  mysql-password: TWlQYXNzd29yZFNlZ3VybzEyMyE=  # MiPasswordSeguro123! (base64 encoded)
  mysql-host: MzQuNjkuMjguMTYy  # 34.69.28.162 (base64 encoded)
