apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-secret
  namespace: todo
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30=  # {} (base64 encoded) - será actualizado por el script

